### ISSUE TITLE
more examples or documentation needed

### ISSUE THREAD

**Issue by hvdort** [lamoni/junosnetconf#2]
I try to use this library to manage our Juniper switches. Connection making and getting information works fine, but how to change a VLAN member on a particular access port?

**Comment by lamoni** [comment]
Hi @hvdort,

To change a VLAN member, you'd need to push configuration. JunosNetConf has this method for pushing set commands:

loadConfigurationSet(array)

As an example, to change an interface description using set commands would be something like this (I don't have an env available to me at the moment so kind of winging it, you can check https://github.com/lamoni/junosnetconf/blob/master/JunosNetConf.php to get an idea of what methods are available to you):

```
$junos = new JunosNetConf(
    "192.168.0.100",
    new NetConfAuthPassword(
        [
            "username" => "lamoni",
            "password" => "phpsux"
        ]
    )
);

$config = Array('set interfaces ge-0/0/0 unit 0 description "test"');
$junos->loadConfigurationSet($config);
$junos->commitConfiguration();
```

**Comment by hvdort** [comment]
Hi @lamoni,

Excellent!! Works like a charm! Thank you very much for your fast response!

Last question: Do you also have an example for the best way of error-checking or is try-catch the way to go?

Regards,
Hugo

**Comment by lamoni** [comment]
@hvdort no problem! glad to :). As for error-checking, it depends on what kind of errors you're thinking about (e.g. for catching failure to connect to the device, you'll want try catch if I remember right, but if you're talking about catching errors with a commit, like if you attempted to push/commit invalid config and you're wanting to check the reason why, you'd want to check the response from "$junos->commitConfiguration()". To be honest, I haven't had to use this library in awhile so my memory might be hazy, forgive me if that is the case.

**Comment by hvdort** [comment]
How easy can it be! Your memory is errorless, the returnvalue contains indeed the answer of the commit.

Many thanks again!
Regards,
Hugo
